### ISSUE TITLE
Hello, is this a project to use pouchdb as the default db for meteor?

### ISSUE THREAD

**Issue by karst10607** [tyler-johnson/pouchdb-subscribe#5]
I have similar requirement and I wish to participate ~

**Comment by tyler-johnson** [comment]
This library is sort of the inverse of that. I really liked the Meteor Collection sync API, but I wasn't using Meteor so I basically duplicated the API on top of PouchDB. At one point it had [Trackr](http://ghub.io/trackr) dependencies, but now it just uses EventEmitter to report changes. One could, however, use those events to integrate with Meteor Tracker and use this library as a replacement to Meteor Collections and Mongo.
